name: AT2

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

# Cancels any in progress 'workflows' associated with this PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  coverage-check:
    uses: ./.github/workflows/ci.yml
    with:
      target-runner-labels: "['self-hosted', 'gcc-12.3.0-openmpi-4.1.6']"
      image: registry-ex.sandia.gov/trilinos-project/trilinos-containers/production/ubi8-gcc-12.3.0-openmpi-4.1.6:20260507
      genconfig-string: "rhel8_gcc-openmpi_debug-coverage_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_all"
      target-branch: "develop"
      cdash-track: "Experimental"
      dashboard-build-name: ${AT2_IMAGE}_debug_shared_coverage
      max-cores-allowed: 48
      num-concurrent-tests: 16

#  gcc12-openmpi4:
#    uses: ./.github/workflows/ci.yml
#    with:
#      target-runner-labels: "['self-hosted', 'gcc-12.3.0-openmpi-4.1.6', '20260507']"
#      genconfig-string: "rhel8_gcc-openmpi_debug_shared_no-kokkos-arch_no-asan_complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables"
#      image: registry-ex.sandia.gov/trilinos-project/trilinos-containers/production/ubi8-gcc-12.3.0-openmpi-4.1.6:20260507
#      cdash-track: "Pull Request"
#      dashboard-build-name: PR-${{ github.event.pull_request.number }}_${AT2_IMAGE}_debug_shared
#      max-cores-allowed: 29
#      num-concurrent-tests: 16
#      target-branch: ${{ github.base_ref }}

