name: Single build and test pipeline

on:
  workflow_call:
    inputs:
      target-runner-labels:
        required: true
        type: string
      genconfig-string:
        required: true
        type: string
      max-cores-allowed:
        description: 'Max cores allowed that is detected on the system.'
        required: true
        type: number
        default: 12
      num-concurrent-tests:
        description: 'Number of concurrent tests allowed in CTest.'
        required: false
        type: number
        default: -1
      slots-per-gpu:
        description: 'On a GPU machine, this is number of slots allowed per GPU. (e.g. 4 allows 4 MPI ranks per GPU)'
        required: false
        type: number
        default: 0
      extra-pr-driver-args:
        description: 'Extra arguments to be used when calling PullRequestLinuxDriverTest.py'
        required: false
        type: string

defaults:
  run:
    shell: bash -l {0}

jobs:
  build-test:
    runs-on: ${{ fromJson(inputs.target-runner-labels) }}
    steps:
      - name: Print workflow inputs
        run: |
          echo "${{ inputs.target-runner-labels}}"
          echo "${{ inputs.genconfig-string }}"
      - name: Print environment
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          env
      - name: Print module list
        run: |
          module list
      - name: Clone Trilinos
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 1
      - name: Print repo status
        run: |
          pwd
          ls -lhat
          git status
          git fetch origin develop
          git branch -vv
          git branch -a
      - name: Print ccache stats
        run: |
          ccache --show-stats --verbose
      - name: Get PR script dependencies
        working-directory: ./packages/framework
        run: |
          mkdir -p /home/Trilinos/build
          ./get_dependencies.sh
      - name: Run build and test driver script
        working-directory: /home/Trilinos/build
        run: |
          pwd
          echo "GenConfig string: ${{ inputs.genconfig-string }}"
          echo "Max cores allowed: ${{ inputs.max-cores-allowed }}"
          echo "Num concurrent test: ${{ inputs.num-concurrent-tests }}"
          echo "Slots per GPU: ${{ inputs.slots-per-gpu }}"
          echo "Extra PR driver args: ${{ inputs.extra-pr-driver-args }}"

      

