name: Trilinos CI Pipeline

on:
  workflow_call:
    inputs:
      target-runner-labels:
        required: true
        type: string
      genconfig-string:
        required: true
        type: string

defaults:
  run:
    shell: bash -l {0}

jobs:
  ci:
    runs-on: ${{ fromJson(inputs.target-runner-labels) }}
    steps:
      - name: Print workflow inputs
        run: |
          echo "${{ inputs.target-runner-labels}}"
          echo "${{ inputs.genconfig-string }}"
      - name: Print environment
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          env
      - name: Print module list
        run: |
          module list
      - name: Clone Trilinos
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 1
      - name: Print repo status
        run: |
          pwd
          ls -lhat
          git status
          git branch -vv
          git branch -a
      - name: Print ccache stats
        run: |
          ccache --show-stats --verbose
      - name: Get PR script dependencies
        working-directory: ./packages/framework
        run: |
          ./get_dependencies.sh

      

