name: Nightly

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  cuda-kokkos-bounds-check:
    uses: ./.github/workflows/ci_pipeline.yml
    with:
      target-runner-labels: "['self-hosted', 'cuda-12.4.1-gcc-12.3.0-openmpi-4.1.6', '20251204', 'gpu:A100']"
      genconfig-string: "rhel_cuda-12-gcc-openmpi_release_static_Ampere80_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables"
      max-cores-allowed: 56
      num-concurrent-tests: 112
      slots-per-gpu: 8
      extra-pr-driver-args: "--skip-run-tests"
